site_name: Trello User Documentation
site_url: https://NathanSite.com
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.footer
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: dark blue
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: dark blue
      accent: deep orange

nav: # Configure order of navigation
  - index.md
  - add-member-to-board.md
  - create-list.md
  - integrate-apps.md
  - troubleshooting.md
  - glossary.md

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

# extra:
#   social:
#     - icon:
#       link: https://www.google.com/
#     - icon:
#       link: https://www.google.com/

copyright: Copyright &copy; 2026 Nathan Hilario
